version: "3"
services:
  shop-ts-node-docker:
    container_name: shop-ts-node-docker
    user: "node"
    working_dir: /home/node/
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - shop-postgres
    restart: always
    volumes:
      - ./src:/home/node/src:ro
      - ./package.json:/home/node/package.json
      - ./tsconfig.json:/home/node/tsconfig.json:ro
    environment:
      DATABASE_URL: postgres://postgres:secret@postgres:5432/shop-db
      NODE_ENV: development
    tty: true
    stdin_open: true
    ports:
      - '5000:5000'
    command: bash -c "npm i && npm run dev"
  shop-postgres:
    container_name: shop-postgres
    image: postgres:12
    ports:
      - "5432:5432"
    volumes: 
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: shop-db
  shop-pgadmin:
    container_name: shop-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: secret@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - shop-postgres
volumes:
    db-data:
    pgadmin-data:
